# Generated by Django 4.2 on 2024-01-31 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_account", "0003_contact_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="user",
        ),
    ]
