# Generated by Django 4.2 on 2024-03-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_profile_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified_email',
        ),
    ]
