# Generated by Django 4.2 on 2024-03-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0008_profile_email_verified_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created',
            new_name='created_at',
        ),
    ]
