# Generated by Django 4.2 on 2024-03-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0009_rename_created_profile_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_verified',
            new_name='is_email_verified',
        ),
    ]
