# Generated by Django 4.2 on 2024-03-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0010_rename_email_verified_profile_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
