# Generated by Django 5.0 on 2023-12-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_price_with_discount_alter_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="img/products"),
        ),
    ]
